"""Command to generate shell completion scripts."""

from __future__ import annotations

import click

from ._utils.formatting import console

# All top-level commands (for completion)
COMMANDS = [
    "agent-savings",
    "agents",
    "audit-reads",
    "benchmark",
    "capture",
    "ccr",
    "compress-read",
    "compress-search",
    "config",
    "copilot-auth",
    "dashboard",
    "diff",
    "doctor",
    "evals",
    "init",
    "install",
    "learn",
    "loc",
    "logs",
    "mcp",
    "memory",
    "output-savings",
    "perf",
    "preset",
    "prioritize",
    "proxy",
    "quickstart",
    "recipe",
    "remove",
    "report",
    "restart",
    "run",
    "savings",
    "service",
    "sg",
    "start",
    "stats",
    "stop",
    "tools",
    "update",
    "version",
    "wrap",
]

# Subcommands for groups
SUBCOMMANDS = {
    "config": ["path", "reset", "set"],
    "init": ["aider", "claude", "codex", "copilot", "cursor", "hook", "openclaw", "opencode"],
    "memory": ["delete", "edit", "export", "import", "list", "prune", "purge", "show", "stats"],
    "service": ["install", "logs", "remove", "status"],
    "wrap": ["aider", "claude", "codex", "continue", "copilot", "cursor", "openclaw", "opencode", "vibe"],
}


def _generate_bash() -> str:
    """Generate bash completion script."""
    cmd_list = " ".join(COMMANDS)
    return f"""#!/usr/bin/env bash
# Copium shell completion for bash
# Generated by: copium completions bash
# Install: copium completions bash >> ~/.bash_completion

_copium_completions() {{
    local cur prev commands
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    commands="{cmd_list}"

    # Global flags
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--help --version --json --quiet --verbose" -- "$cur") )
        return 0
    fi

    # Subcommand completion
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
    fi

    # Group subcommands
    local group="${{COMP_WORDS[1]}}"
    case "$group" in
        config)
            COMPREPLY=( $(compgen -W "path reset set" -- "$cur") )
            ;;
        init)
            COMPREPLY=( $(compgen -W "aider claude codex copilot cursor hook openclaw opencode" -- "$cur") )
            ;;
        memory)
            COMPREPLY=( $(compgen -W "delete edit export import list prune purge show stats" -- "$cur") )
            ;;
        service)
            COMPREPLY=( $(compgen -W "install logs remove status" -- "$cur") )
            ;;
        wrap)
            COMPREPLY=( $(compgen -W "aider claude codex continue copilot cursor openclaw opencode vibe" -- "$cur") )
            ;;
    esac

    return 0
}}

complete -F _copium_completions copium
"""


def _generate_zsh() -> str:
    """Generate zsh completion script."""
    return """#compdef copium

# Copium shell completion for zsh
# Generated by: copium completions zsh
# Install: copium completions zsh >> ~/.zshrc

_copium() {
    local -a commands
    
    commands=(
        'agent-savings:Render or verify token savings'
        'agents:List detected AI agents and wrap status'
        'audit-reads:Audit Read-tool traffic'
        'benchmark:Run A/B benchmark comparing configs'
        'capture:Capture network traffic'
        'ccr:CCR debugging commands'
        'compress-read:Compress Read tool output'
        'compress-search:Compress Grep tool output'
        'config:Show/edit configuration'
        'copilot-auth:Manage GitHub Copilot OAuth'
        'dashboard:Live terminal dashboard'
        'diff:Run structural diff'
        'doctor:Diagnose installation'
        'evals:Memory evaluation commands'
        'init:Install durable integrations'
        'install:Manage deployments'
        'learn:Learn from past failures'
        'loc:Lines-of-code probe'
        'logs:Tail proxy logs'
        'mcp:MCP server integration'
        'memory:Manage stored memories'
        'output-savings:Show output-token reduction'
        'perf:Analyze performance logs'
        'preset:Apply compression preset'
        'prioritize:Rank files by importance'
        'proxy:Start optimization proxy'
        'quickstart:Interactive setup wizard'
        'recipe:Manage compression recipes'
        'remove:Fully remove Copium'
        'report:Generate analytics report'
        'restart:Restart background daemon'
        'run:Zero-config proxy start'
        'savings:Show compression savings'
        'service:Manage system service'
        'sg:Run ast-grep'
        'start:Start background daemon'
        'stats:Show compression statistics'
        'stop:Stop the daemon'
        'tools:Passthrough tool commands'
        'update:Update to latest release'
        'version:Show version info'
        'wrap:Wrap CLI tools for Copium'
    )

    _arguments -C \
        '--help[Show help]' \
        '-?[Show help]' \
        '--version[Show version]' \
        '-v[Show version]' \
        '*:: :->args'

    case $state in
        args)
            _describe 'command' commands
            ;;
    esac
}

_copium "$@"
"""


def _generate_fish() -> str:
    """Generate fish completion script."""
    cmds = "\n".join(f"complete -c copium -f -n '__fish_use_subcommand' -a '{c}' -d ''" for c in COMMANDS)
    return f"""# Copium shell completion for fish
# Generated by: copium completions fish
# Install: copium completions fish > ~/.config/fish/completions/copium.fish

# Global flags
complete -c copium -l help -s '?' -d 'Show help'
complete -c copium -l version -s v -d 'Show version'
complete -c copium -l json -d 'Output as JSON'
complete -c copium -l quiet -s q -d 'Suppress non-error output'
complete -c copium -l verbose -s v -d 'Show verbose output'

# Top-level commands
{cmds}

# config subcommands
complete -c copium -n '__fish_seen_subcommand_from config' -a 'path' -d 'Show config file location'
complete -c copium -n '__fish_seen_subcommand_from config' -a 'reset' -d 'Reset to defaults'
complete -c copium -n '__fish_seen_subcommand_from config' -a 'set' -d 'Set a config value'

# init subcommands
complete -c copium -n '__fish_seen_subcommand_from init' -a 'aider' -d 'Initialize Aider'
complete -c copium -n '__fish_seen_subcommand_from init' -a 'claude' -d 'Initialize Claude Code'
complete -c copium -n '__fish_seen_subcommand_from init' -a 'codex' -d 'Initialize Codex'
complete -c copium -n '__fish_seen_subcommand_from init' -a 'copilot' -d 'Initialize Copilot'
complete -c copium -n '__fish_seen_subcommand_from init' -a 'cursor' -d 'Initialize Cursor'
complete -c copium -n '__fish_seen_subcommand_from init' -a 'openclaw' -d 'Initialize OpenClaw'
complete -c copium -n '__fish_seen_subcommand_from init' -a 'opencode' -d 'Initialize OpenCode'

# memory subcommands
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'delete' -d 'Delete a memory'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'edit' -d 'Edit a memory'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'export' -d 'Export memories'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'import' -d 'Import memories'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'list' -d 'List memories'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'prune' -d 'Prune old memories'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'purge' -d 'Purge all memories'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'show' -d 'Show a memory'
complete -c copium -n '__fish_seen_subcommand_from memory' -a 'stats' -d 'Show memory statistics'

# service subcommands
complete -c copium -n '__fish_seen_subcommand_from service' -a 'install' -d 'Install system service'
complete -c copium -n '__fish_seen_subcommand_from service' -a 'logs' -d 'Tail service logs'
complete -c copium -n '__fish_seen_subcommand_from service' -a 'remove' -d 'Uninstall system service'
complete -c copium -n '__fish_seen_subcommand_from service' -a 'status' -d 'Show service health'

# wrap subcommands
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'aider' -d 'Wrap Aider'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'claude' -d 'Wrap Claude Code'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'codex' -d 'Wrap Codex'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'continue' -d 'Wrap Continue'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'copilot' -d 'Wrap Copilot'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'cursor' -d 'Wrap Cursor'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'openclaw' -d 'Wrap OpenClaw'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'opencode' -d 'Wrap OpenCode'
complete -c copium -n '__fish_seen_subcommand_from wrap' -a 'vibe' -d 'Wrap Vibe'
"""


def _generate_powershell() -> str:
    """Generate PowerShell completion script."""
    cmd_list = ", ".join(f"'{c}'" for c in COMMANDS)
    return f"""# Copium shell completion for PowerShell
# Generated by: copium completions powershell
# Install: copium completions powershell | Out-String | Invoke-Expression

Register-ArgumentCompleter -Native -CommandName 'copium' -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @({cmd_list})

    $results = @()
    foreach ($cmd in $commands) {{
        if ($cmd -like "$wordToComplete*") {{
            $results += [System.Management.Automation.CompletionResult]::new(
                $cmd,
                $cmd,
                'ParameterValue',
                $cmd
            )
        }}
    }}

    $results
}}
"""


@click.command()
@click.argument("shell", type=click.Choice(["bash", "zsh", "fish", "powershell"]))
def completions(shell: str) -> None:
    """Generate shell completion scripts.

    Outputs a completion script to stdout. Redirect to the appropriate
    file to install.

    \b
    Examples:
        copium completions bash >> ~/.bash_completion
        copium completions zsh >> ~/.zshrc
        copium completions fish > ~/.config/fish/completions/copium.fish
        copium completions powershell | Out-String | Invoke-Expression

    \b
    After installing, reload your shell or run:
        source ~/.bash_completion   # bash
        source ~/.zshrc             # zsh
        exec fish                   # fish
    """
    generators = {
        "bash": _generate_bash,
        "zsh": _generate_zsh,
        "fish": _generate_fish,
        "powershell": _generate_powershell,
    }

    script = generators[shell]()
    click.echo(script)

    # Show installation hint
    hints = {
        "bash": "copium completions bash >> ~/.bash_completion",
        "zsh": "copium completions zsh >> ~/.zshrc",
        "fish": "copium completions fish > ~/.config/fish/completions/copium.fish",
        "powershell": "copium completions powershell | Out-String | Invoke-Expression",
    }

    console.print(
        f"\n[dim]Install with: [bold]{hints[shell]}[/bold][/dim]"
    )
