"""Adaptive compression engine for local models.

Automatically adjusts compression aggressiveness based on available
VRAM, context utilization, and KV cache precision. Keeps the model
in the "Smart Zone" (0-40% context utilization) where performance
is optimal.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from enum import Enum
from typing import Any

from copium.integrations.local.vram_monitor import VRAMMonitor, VRAMStatus

logger = logging.getLogger(__name__)


class CompressionLevel(str, Enum):
    """Compression aggressiveness levels."""

    LIGHT = "light"
    STANDARD = "standard"
    AGGRESSIVE = "aggressive"
    MAXIMUM = "maximum"


@dataclass
class AdaptiveConfig:
    """Configuration generated by the adaptive compression engine."""

    level: CompressionLevel
    transforms: list[str]
    ccr_enabled: bool = True
    ccr_storage: str = "memory"
    ml_compressor: bool = False
    smart_zone_target_pct: float = 0.4
    reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict for proxy configuration."""
        return {
            "compression_aggressiveness": self.level.value,
            "transforms": self.transforms,
            "ccr_enabled": self.ccr_enabled,
            "ccr_storage": self.ccr_storage,
            "ml_compressor": self.ml_compressor,
            "smart_zone_target_pct": self.smart_zone_target_pct,
        }


class AdaptiveCompressor:
    """Automatically adjust compression based on system resources.

    Monitors VRAM usage and context utilization to dynamically
    select the optimal compression configuration.

    Usage:
        compressor = AdaptiveCompressor()
        config = compressor.get_config()
        # Use config.transforms, config.level, etc.

        # Or get config for a specific context size
        config = compressor.get_config_for_context(context_size=8192)
    """

    def __init__(self, vram_monitor: VRAMMonitor | None = None):
        self._monitor = vram_monitor or VRAMMonitor()

    def get_config(self) -> AdaptiveConfig:
        """Get compression config based on current VRAM state."""
        status = self._monitor.get_status()
        return self._config_from_vram(status)

    def get_config_for_context(
        self,
        context_size: int,
        context_used: int = 0,
        kv_cache_precision: str = "fp16",
    ) -> AdaptiveConfig:
        """Get compression config based on context constraints.

        Args:
            context_size: Total context window size in tokens
            context_used: Currently used tokens
            kv_cache_precision: KV cache quantization level
        """
        utilization = context_used / context_size if context_size > 0 else 0.0

        # KV cache precision multiplier
        precision_multiplier = {
            "fp16": 1.0,
            "bf16": 1.0,
            "fp8": 1.2,
            "q8_0": 1.3,
            "q5_k_m": 1.4,
            "q5_0": 1.5,
            "q4_k_m": 1.8,
            "q4_0": 2.0,
        }.get(kv_cache_precision, 1.0)

        # Effective utilization accounts for precision loss
        effective_utilization = min(1.0, utilization * precision_multiplier)

        if effective_utilization > 0.7:
            return self._maximum_config(
                f"Context at {utilization:.0%}, KV={kv_cache_precision}"
            )
        elif effective_utilization > 0.4:
            return self._aggressive_config(
                f"Context at {utilization:.0%}, exiting Smart Zone"
            )
        elif context_size <= 8192:
            return self._aggressive_config(
                f"Small context window ({context_size} tokens)"
            )
        elif context_size <= 32768:
            return self._standard_config(
                f"Medium context window ({context_size} tokens)"
            )
        else:
            return self._light_config(
                f"Large context window ({context_size} tokens)"
            )

    def _config_from_vram(self, status: VRAMStatus) -> AdaptiveConfig:
        """Generate config from VRAM status."""
        if status.total_mb == 0:
            # Can't detect VRAM — use standard config
            return self._standard_config("VRAM not detectable")

        free_pct = status.free_fraction

        if free_pct > 0.5:
            return self._light_config(
                f"Plenty of VRAM ({status.free_mb}MB free)"
            )
        elif free_pct > 0.3:
            return self._standard_config(
                f"Moderate VRAM ({status.free_mb}MB free)"
            )
        elif free_pct > 0.15:
            return self._aggressive_config(
                f"Low VRAM ({status.free_mb}MB free)"
            )
        else:
            return self._maximum_config(
                f"Critical VRAM ({status.free_mb}MB free)"
            )

    def _light_config(self, reason: str) -> AdaptiveConfig:
        """Light compression — plenty of resources."""
        return AdaptiveConfig(
            level=CompressionLevel.LIGHT,
            transforms=["SmartCrusher", "SessionDedup"],
            ccr_enabled=False,
            ml_compressor=False,
            reason=reason,
        )

    def _standard_config(self, reason: str) -> AdaptiveConfig:
        """Standard compression — balanced."""
        return AdaptiveConfig(
            level=CompressionLevel.STANDARD,
            transforms=[
                "SmartCrusher",
                "SessionDedup",
                "ErrorCompressor",
                "LogCompressor",
            ],
            ccr_enabled=True,
            ccr_storage="memory",
            ml_compressor=False,
            reason=reason,
        )

    def _aggressive_config(self, reason: str) -> AdaptiveConfig:
        """Aggressive compression — constrained resources."""
        return AdaptiveConfig(
            level=CompressionLevel.AGGRESSIVE,
            transforms=[
                "SmartCrusher",
                "SessionDedup",
                "ErrorCompressor",
                "LogCompressor",
                "DiffCompressor",
                "SearchCompressor",
            ],
            ccr_enabled=True,
            ccr_storage="memory",
            ml_compressor=False,
            smart_zone_target_pct=0.35,
            reason=reason,
        )

    def _maximum_config(self, reason: str) -> AdaptiveConfig:
        """Maximum compression — critical resource constraints."""
        return AdaptiveConfig(
            level=CompressionLevel.MAXIMUM,
            transforms=[
                "SmartCrusher",
                "SessionDedup",
                "ErrorCompressor",
                "LogCompressor",
                "DiffCompressor",
                "SearchCompressor",
            ],
            ccr_enabled=True,
            ccr_storage="memory",
            ml_compressor=False,
            smart_zone_target_pct=0.3,
            reason=reason,
        )
